name: panel_data_models_with_fixed_effects
channels:
  - pytask
  - conda-forge

  - r

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - matplotlib
  - pandas
  - pip
  - pytask>=0.0.11
  - pytask-latex>=0.0.10
  - linearmodels
  - scipy

  - pytask-r>=0.0.6


  - pytest
  - pytest-cov
  - python=3.8
  - python-graphviz

  - r-aer
  - r-aod
  - r-base
  - r-car
  - r-essentials
  - r-rjson
  - r-lmtest
  - r-sandwich
  - r-ggplot2
  - r-rjson
  - r-dplyr


  - virtualenv=20.0.33

  - pip:

    - pre-commit

    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
